### ISSUE TITLE
US: As a user I want to be able to create a post for a conference 

### ISSUE THREAD

**Issue by Jumaruba** [FEUP-ESOF-2020-21/open-cx-t4g2-codemasters#22]
As a user I want to be able to create a post for a conference
Acceptance test:
Scenario: A user wants to create a post
Given: A button that allows them to do so
When: The user taps that button
Then: The user is taken to the post creation page
Value: Must have
Effort: L

**Comment by matosjoaops** [comment]
Implemented in #67 and #68
