### ISSUE TITLE
US: As a user I want to be able to interact with the feed results (pick one and go to the respective page)

### ISSUE THREAD

**Issue by 2dukes** [FEUP-ESOF-2020-21/open-cx-t4g2-codemasters#36]
As a user I want to be able to interact with the feed results (pick one and go to the respective page)
Acceptance test:
Scenario: A user is looking at a feed
Given: The conferences shown are clickable
When: The user taps a conference
Then: The user is taken to the page that corresponds to that conference
Value: Must have
Effort: M

**Comment by matosjoaops** [comment]
Implemented with #58
